### ISSUE TITLE
Rename libabigail.yml to runtask.yml in develop branch

### ISSUE THREAD

**Issue by mkrizek** [sinnykumari/task-libabigail#2]
We're changing how the tasks are triggered in taskotron infrastructure and changed our tasks to have the formula file named "runtask.yml" in develop branch. Could you please do the same? Sorry for inconvenience. Thanks!

**Comment by sinnykumari** [comment]
Thanks @mkrizek  for update. I have renamed libabigail.yaml to runtask.yaml 
This request has been fixed with commit https://github.com/sinnykumari/task-libabigail/commit/17c30a17618c9c0a4849fb56bdbf2ce47ada5c54
